[package]
name = "gurih_dsl"
version = "0.1.0"
edition = "2024"

[dependencies]
annotate-snippets = "0.12"
gurih_ir = { version = "0.1.0", path = "../gurih_ir" }
kdl = "6.5.0"
miette = { version = "7.6.0", features = ["fancy"] }
thiserror = "2.0.18"
