[package]
name = "gurih_dsl"
version = "0.1.0"
edition = "2024"

[dependencies]
annotate-snippets = { workspace = true }
gurih_ir = { workspace = true }
kdl = { workspace = true }
miette = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
