[package]
name = "gurih_ir"
version = "0.1.0"
edition = "2024"

[dependencies]
gurih_common = { version = "0.1.0", path = "../gurih_common" }
serde = { workspace = true }
serde_json = { workspace = true }
symbol_table = {workspace = true }
