[package]
name = "gurih_runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
gurih_common = { workspace = true }
gurih_ir = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
