[package]
name = "gurih_runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
gurih_common = { version = "0.1.0", path = "../gurih_common" }
gurih_ir = { version = "0.1.0", path = "../gurih_ir" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio", "tls-native-tls"] }
tokio = { version = "1.49.0", features = ["full"] }
uuid = { version = "1.19.0", features = ["v4", "fast-rng"] }
